In [1]:
import pandas as pd

# Data Frame in Pandas

In [2]:
info={
    "name" : ["Talha","Umer","Abdullah"],
    "cgpa" : [3.24,3.12,3.9]
}
df=pd.DataFrame(info)
print(df)

       name  cgpa
0     Talha  3.24
1      Umer  3.12
2  Abdullah  3.90

# Series in pandas

In [3]:
s=pd.Series([1,2,3,4,5,6,7])
print(s)
# index
print(s[2])

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64
3

In [4]:
s=pd.Series([23,24,25],index=['Talha','Umar','Abdullah'])
print(s)
print(s["Talha"])
print(s["Umar"])
print(s[0])
print(s.index)

Talha       23
Umar        24
Abdullah    25
dtype: int64
23
24
23
Index(['Talha', 'Umar', 'Abdullah'], dtype='object')

C:\Users\DELL\AppData\Local\Temp\ipykernel_10184\2955455170.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

# Series properties

In [5]:
# Homogenous
s=pd.Series([23,24,25,"abc"],index=['Talha','Umar','Abdullah','abdul'])
print(s)

Talha        23
Umar         24
Abdullah     25
abdul       abc
dtype: object

In [6]:
# vectorized opertation
s1=pd.Series([23,24,25])
s2=pd.Series([1,1,1])
            
print(s1 + s2)
# muteable
s1[1]=27
print(s1)

0    24
1    25
2    26
dtype: int64
0    23
1    27
2    25
dtype: int64

In [7]:
# immutable size
s3=pd.Series([23,24,25])
s3[0]=100
changed_s3=s3.drop(0)
print(s3)
print(changed_s3)

0    100
1     24
2     25
dtype: int64
1    24
2    25
dtype: int64

# DataFrame (2D Labeled Array)

In [8]:
# creating DataFrame with dictonary of list
info={
    "name" : ["Talha","Umer","Abdullah"],
    "cgpa" : [3.24,3.12,3.9]
}
df=pd.DataFrame(info)
print(df)
print(df.index)
print(df.columns)

       name  cgpa
0     Talha  3.24
1      Umer  3.12
2  Abdullah  3.90
RangeIndex(start=0, stop=3, step=1)
Index(['name', 'cgpa'], dtype='object')

In [9]:
# with list of list method
df=pd.DataFrame([["Talha",24],["Umar",25],["Abdul",26]],columns=["Nmae","Age"])
print(df)

    Nmae  Age
0  Talha   24
1   Umar   25
2  Abdul   26

In [10]:
# With Numpy Arrays
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
df=pd.DataFrame(arr,columns=["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [11]:
df=pd.read_csv("global_air_quality_data_10000.csv")
print(df)

                City       Country        Date   PM2.5    PM10    NO2    SO2  \
0            Bangkok      Thailand  2023-03-19   86.57   25.19  99.88  30.63
1           Istanbul        Turkey  2023-02-16   50.63   97.39  48.14   8.71
2     Rio de Janeiro        Brazil  2023-11-13  130.21   57.22  98.51   9.92
3             Mumbai         India  2023-03-16  119.70  130.52  10.96  33.03
4              Paris        France  2023-04-04   55.20   36.62  76.85  21.85
...              ...           ...         ...     ...     ...    ...    ...
9995    Johannesburg  South Africa  2023-09-16  147.85  184.34  90.33  34.93
9996          Berlin       Germany  2023-12-05   12.22  121.49  49.04   5.66
9997          Moscow        Russia  2023-11-26   44.07  143.62   8.41  32.58
9998          Berlin       Germany  2023-02-03   67.43   96.79  43.23  29.19
9999         Bangkok      Thailand  2023-06-13   16.34   28.80  50.48  21.20

        CO      O3  Temperature  Humidity  Wind Speed
0     4.46   36.29        17.67     59.35       13.76
1     3.40  144.16         3.46     67.51        6.36
2     0.12  179.31        25.29     29.30       12.87
3     7.74   38.65        23.15     99.97        7.71
4     2.00   67.09        16.02     90.28       14.16
...    ...     ...          ...       ...         ...
9995  2.81  191.45        -1.92     65.22       15.48
9996  2.10  184.56        -9.81     12.16       10.75
9997  0.69  167.68        39.35     53.95        4.56
9998  6.01  148.50        26.21     58.54        2.71
9999  0.49   17.41         2.50     66.05        5.01

[10000 rows x 12 columns]

In [12]:
df.head()

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
0,Bangkok,Thailand,2023-03-19,86.57,25.19,99.88,30.63,4.46,36.29,17.67,59.35,13.76
1,Istanbul,Turkey,2023-02-16,50.63,97.39,48.14,8.71,3.40,144.16,3.46,67.51,6.36
2,Rio de Janeiro,Brazil,2023-11-13,130.21,57.22,98.51,9.92,0.12,179.31,25.29,29.30,12.87
3,Mumbai,India,2023-03-16,119.70,130.52,10.96,33.03,7.74,38.65,23.15,99.97,7.71
4,Paris,France,2023-04-04,55.20,36.62,76.85,21.85,2.00,67.09,16.02,90.28,14.16

In [13]:
df.tail()

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
9995,Johannesburg,South Africa,2023-09-16,147.85,184.34,90.33,34.93,2.81,191.45,-1.92,65.22,15.48
9996,Berlin,Germany,2023-12-05,12.22,121.49,49.04,5.66,2.10,184.56,-9.81,12.16,10.75
9997,Moscow,Russia,2023-11-26,44.07,143.62,8.41,32.58,0.69,167.68,39.35,53.95,4.56
9998,Berlin,Germany,2023-02-03,67.43,96.79,43.23,29.19,6.01,148.50,26.21,58.54,2.71
9999,Bangkok,Thailand,2023-06-13,16.34,28.80,50.48,21.20,0.49,17.41,2.50,66.05,5.01

In [14]:
df.describe()

,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000
mean,77.448439,104.438161,52.198649,25.344490,5.047984,106.031643,14.89715,55.078579,10.231636
std,41.927871,55.062396,27.320490,14.091194,2.852625,55.081345,14.44380,25.982232,5.632628
min,5.020000,10.000000,5.010000,1.000000,0.100000,10.040000,-10.00000,10.010000,0.500000
25%,41.185000,57.137500,28.347500,13.190000,2.560000,58.380000,2.25750,32.527500,5.290000
50%,77.725000,103.690000,52.100000,25.350000,5.090000,106.055000,14.75500,55.080000,10.260000
75%,113.392500,152.265000,75.705000,37.500000,7.480000,153.982500,27.38250,77.442500,15.070000
max,149.980000,200.000000,100.000000,49.990000,10.000000,200.000000,40.00000,99.990000,20.000000

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   City         10000 non-null  object
 1   Country      10000 non-null  object
 2   Date         10000 non-null  object
 3   PM2.5        10000 non-null  float64
 4   PM10         10000 non-null  float64
 5   NO2          10000 non-null  float64
 6   SO2          10000 non-null  float64
 7   CO           10000 non-null  float64
 8   O3           10000 non-null  float64
 9   Temperature  10000 non-null  float64
 10  Humidity     10000 non-null  float64
 11  Wind Speed   10000 non-null  float64
dtypes: float64(9), object(3)
memory usage: 937.6+ KB

In [16]:
df.columns

Index(['City', 'Country', 'Date', 'PM2.5', 'PM10', 'NO2', 'SO2', 'CO', 'O3',
       'Temperature', 'Humidity', 'Wind Speed'],
      dtype='object')

In [17]:
df.shape

(10000, 12)

In [18]:
df.sample(2)

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
7349,Cairo,Egypt,2023-01-08,61.38,107.74,73.60,20.23,3.66,120.71,23.36,85.93,16.03
6417,Bangkok,Thailand,2023-12-17,68.73,188.79,6.99,35.08,0.11,175.53,-7.87,41.74,8.04

In [19]:
# selecting the data
# label based access(column wise)
df['City']
df[['City','SO2']]
# rows(label based access)
df.loc[0]
df.loc[0:2]
# index based access
df.iloc[0]
df.iloc[0:2]
# accessing the full cel,rowor column by label
df.loc[0,['City','SO2']]
df.loc[0:2,['City','SO2']]

             City    SO2
0         Bangkok  30.63
1        Istanbul   8.71
2  Rio de Janeiro   9.92

In [20]:
# accessing the full cel,rowor column by index
df.columns

df.iloc[0,[0,4]]
df.iloc[0:3, 1:4]

    Country        Date   PM2.5
0  Thailand  2023-03-19   86.57
1    Turkey  2023-02-16   50.63
2    Brazil  2023-11-13  130.21

In [21]:
df.at[0,'City']  #accessing particuler column value by label
df.iat[0,1]     #accessing particuler column value by index

'Thailand'

In [22]:
# Filtering of Data
Co_data=df[(df["CO"] < 3) & (df["SO2"] < 3)] [['City','SO2','CO']]
Co_data.iloc[0]
Co_data.loc[0]    # diff between indexing and labelling

KeyError: 0

# Query method to filter data

In [23]:
co_data=df.query("CO < 5 & SO2 < 20")[['Country','City']].copy()
co_data

          Country            City
1          Turkey        Istanbul
2          Brazil  Rio de Janeiro
7             USA        New York
11         Brazil  Rio de Janeiro
18         Turkey        Istanbul
...           ...             ...
9970        Spain          Madrid
9981          USA     Los Angeles
9986  South Korea           Seoul
9992       Brazil  Rio de Janeiro
9996      Germany          Berlin

[1952 rows x 2 columns]

In [24]:
df

,City,Country,Date,PM2.5,PM10,NO2,SO2,CO,O3,Temperature,Humidity,Wind Speed
0,Bangkok,Thailand,2023-03-19,86.57,25.19,99.88,30.63,4.46,36.29,17.67,59.35,13.76
1,Istanbul,Turkey,2023-02-16,50.63,97.39,48.14,8.71,3.40,144.16,3.46,67.51,6.36
2,Rio de Janeiro,Brazil,2023-11-13,130.21,57.22,98.51,9.92,0.12,179.31,25.29,29.30,12.87
3,Mumbai,India,2023-03-16,119.70,130.52,10.96,33.03,7.74,38.65,23.15,99.97,7.71
4,Paris,France,2023-04-04,55.20,36.62,76.85,21.85,2.00,67.09,16.02,90.28,14.16
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,Johannesburg,South Africa,2023-09-16,147.85,184.34,90.33,34.93,2.81,191.45,-1.92,65.22,15.48
9996,Berlin,Germany,2023-12-05,12.22,121.49,49.04,5.66,2.10,184.56,-9.81,12.16,10.75
9997,Moscow,Russia,2023-11-26,44.07,143.62,8.41,32.58,0.69,167.68,39.35,53.95,4.56
9998,Berlin,Germany,2023-02-03,67.43,96.79,43.23,29.19,6.01,148.50,26.21,58.54,2.71
9999,Bangkok,Thailand,2023-06-13,16.34,28.80,50.48,21.20,0.49,17.41,2.50,66.05,5.01

# cleaning our data(Pandas)

In [25]:
df=pd.read_csv("raw_data.csv")
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [26]:
df.isnull()
df.isna()

       id   name    age  country  gender  income
0   False  False  False    False   False   False
1   False  False  False    False   False   False
2   False  False   True    False   False   False
3   False  False   True    False   False   False
4   False  False  False    False   False    True
5   False  False  False    False   False   False
6   False   True  False    False   False   False
7   False  False  False     True   False   False
8   False  False  False    False   False   False
9   False  False   True    False   False   False
10  False  False  False    False    True   False

In [27]:
df.isnull().sum() # count num of missing value per col

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [28]:
df.dropna()    # by default remove row which have missing value

   id        name   age country  gender   income
0   1    John Doe  29.0     USA    Male  55000.0
1   1    John Doe  29.0     USA    Male  55000.0
5   5      Li Wei  27.0   China    Male  51000.0
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [29]:
df.dropna(axis=1)

    id
0    1
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
10  10

In [30]:
df.fillna(0)  # will fill every missing value with o

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [31]:
# replace by mean value
filled_data=df['age'].fillna(df['age'].mean())
cleaned_data=df.copy()
cleaned_data['age']=cleaned_data['age'].fillna(filled_data)
cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [32]:
df.ffill()
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

# handle duplicate value

In [33]:
df.duplicated()

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
dtype: bool

In [34]:
df.drop_duplicates()  #inplace=True

cleaned_data=cleaned_data.drop_duplicates()
cleaned_data

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female      NaN
5    5        Li Wei  27.00   China     Male  51000.0
6    6           NaN  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     NaN     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [35]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [36]:
# Handle data types
df.dtypes

id           int64
name        object
age        float64
country     object
gender      object
income     float64
dtype: object

In [37]:
df2=df.copy()
df2=df2.fillna(0)
df2['age']=df2['age'].astype('int64')  # it will change the data type of age column
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [38]:
date_str=pd.Series([pd.to_datetime("2026-2-25")])
print(date_str.dtypes)

datetime64[ns]

In [39]:
# Hndle strings while cleaning data
df['gender'].str.lower()
df['gender'].str.upper()
df['gender'].str.capitalize()

0        Male
1        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10        NaN
Name: gender, dtype: object

In [40]:
df['name'].str.split('@')

0         [John Doe]
1         [John Doe]
2       [Jane Smith]
3             [Alex]
4     [Maria Garcia]
5           [Li Wei]
6                NaN
7       [Ahmed Khan]
8       [Rachel Lee]
9      [Carlos Ruiz]
10     [Emily Davis]
Name: name, dtype: object

In [41]:
df['country'].str.contains("USA",case=False)

0      True
1      True
2     False
3      True
4     False
5     False
6     False
7       NaN
8      True
9     False
10     True
Name: country, dtype: object

# Transforming Data (Feature Engineering)

In [42]:
df2=df.copy()
df2['tax']=df2['income'].apply(lambda x: "20%" if x >= 50000 else "10%")
df2

    id          name   age country   gender   income  tax
0    1      John Doe  29.0     USA     Male  55000.0  20%
1    1      John Doe  29.0     USA     Male  55000.0  20%
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%
3    3          Alex   NaN     USA  Unknown  47000.0  10%
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%
5    5        Li Wei  27.0   China     Male  51000.0  20%
6    6           NaN  45.0   India   Female  73000.0  20%
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%

In [43]:
# creat a new column by actually assigning them a new value
df2=df2.assign(new_income=df2['income']*1.1)
df2

    id          name   age country   gender   income  tax  new_income
0    1      John Doe  29.0     USA     Male  55000.0  20%     60500.0
1    1      John Doe  29.0     USA     Male  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%     68200.0
3    3          Alex   NaN     USA  Unknown  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%         NaN
5    5        Li Wei  27.0   China     Male  51000.0  20%     56100.0
6    6           NaN  45.0   India   Female  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%     74800.0
8    8    Rachel Lee  29.0     USA   Female  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%     49500.0
10  10   Emily Davis  31.0     USA      NaN  58000.0  20%     63800.0

In [44]:
# replace some old value with new
df2['country']=df2['country'].replace('USA','US')
df2

    id          name   age country   gender   income  tax  new_income
0    1      John Doe  29.0      US     Male  55000.0  20%     60500.0
1    1      John Doe  29.0      US     Male  55000.0  20%     60500.0
2    2    Jane Smith   NaN  Canada   Female  62000.0  20%     68200.0
3    3          Alex   NaN      US  Unknown  47000.0  10%     51700.0
4    4  Maria Garcia  34.0   Spain   Female      NaN  10%         NaN
5    5        Li Wei  27.0   China     Male  51000.0  20%     56100.0
6    6           NaN  45.0   India   Female  73000.0  20%     80300.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0  20%     74800.0
8    8    Rachel Lee  29.0      US   Female  62000.0  20%     68200.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0  10%     49500.0
10  10   Emily Davis  31.0      US      NaN  58000.0  20%     63800.0

# Task: Shif id column at last

In [45]:
df2=df.copy()
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [46]:
col_order=[col for col in df2.columns if col != "id"] +["id"]
print(col_order)
df2[col_order]

['name', 'age', 'country', 'gender', 'income', 'id']

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
1       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   NaN  Canada   Female  62000.0   2
3           Alex   NaN     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      NaN   4
5         Li Wei  27.0   China     Male  51000.0   5
6            NaN  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0     NaN     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   NaN  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA      NaN  58000.0  10

In [47]:
df2=df.copy()
df2

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [48]:
df2=df2.drop_duplicates()
df2.fillna(0)
df2=df2.sort_values("income")
df2=df2.reset_index(drop=True)
df2 .to_csv("Sorted_data.csv")

# group by Aggregation

In [49]:
df.groupby("country")["income"].mean()
df.groupby("country")["income"].min()
df.groupby("country")["income"].max()

country
Canada    62000.0
China     51000.0
India     73000.0
Mexico    45000.0
Spain         NaN
USA       62000.0
Name: income, dtype: float64

In [50]:
df.groupby("country")["income"].agg(["mean","min","max"])
df.groupby("country")["income"].aggregate(["mean","min","max"])

            mean      min      max
country
Canada   62000.0  62000.0  62000.0
China    51000.0  51000.0  51000.0
India    73000.0  73000.0  73000.0
Mexico   45000.0  45000.0  45000.0
Spain        NaN      NaN      NaN
USA      55400.0  47000.0  62000.0

In [51]:
df.groupby("country").agg({
    "income" : "mean",
    "age" : "mean"
})



df.groupby("country").agg({
    "income" : "max",
    "age" : "mean"
})

          income   age
country
Canada   62000.0   NaN
China    51000.0  27.0
India    73000.0  45.0
Mexico   45000.0   NaN
Spain        NaN  34.0
USA      62000.0  29.5

In [52]:
df.groupby("country").agg(
    max_income=("income","max"),
    avg_salary=("age","mean")
)

         max_income  avg_salary
country
Canada      62000.0         NaN
China       51000.0        27.0
India       73000.0        45.0
Mexico      45000.0         NaN
Spain           NaN        34.0
USA         62000.0        29.5

# Merging and joining data

In [59]:
df_customer=pd.DataFrame({
    "customer_id" : [1,2,3,4,5],
    "customer_name" : ["Talha","Umer","Ahsan","M","T"]
})


df_order_id=pd.DataFrame({
    "order_id" : [1,2,3,4,5],
    "customer_id" : [2,4,5,3,1],
    "amount" : [1200,1300,1400,1500,1600]
})

pd.merge(df_customer,df_order_id,on="customer_id")   #inner joining
pd.merge(df_customer,df_order_id,on="customer_id",how="left")   #left joining
pd.merge(df_customer,df_order_id,on="customer_id",how="right")   #right joining
pd.merge(df_customer,df_order_id,on="customer_id",how="outer")   #outer joining

   customer_id customer_name  order_id  amount
0            1         Talha         5    1600
1            2          Umer         1    1200
2            3         Ahsan         4    1500
3            4             M         2    1300
4            5             T         3    1400

In [55]:
df_customer

   customer_id customer_name
0            1         Talha
1            2          Umer
2            3         Ahsan
3            4             M
4            5             T

# Concatenation in pandas

In [64]:
df_customer=pd.DataFrame({
    "customer_id" : [1,2,3,4,5],
    "customer_name" : ["Talha","Umer","Ahsan","M","T"]
})


df_order_id=pd.DataFrame({
    "order_id" : [1,2,3,4,5],
    "customer_id" : [2,4,5,3,1],
    "amount" : [1200,1300,1400,1500,1600]
})
pd.concat([df_customer,df_order_id]    # row wise
pd.concat([df_customer,df_order_id],axis=1)   #col wise concat

   customer_id customer_name  order_id  customer_id  amount
0            1         Talha         1            2    1200
1            2          Umer         2            4    1300
2            3         Ahsan         3            5    1400
3            4             M         4            3    1500
4            5             T         5            1    1600