In [1]:
import requests
from bs4 import BeautifulSoup

In [6]:
# # Extract and load Data
# import os

# os.makedirs("scrape_data_p", exist_ok=True)

page_count = 1

while True:
    URL = f"https://quotes.toscrape.com/page/{page_count}/"
    res = requests.get(URL)
    soup = BeautifulSoup(res.text, "lxml")
    quotes = soup.select("div.quote")

    if not quotes:
        print("No more pages left 🚫")
        break

    with open(f"web_scraping_projects/quotes{page_count}.html", "w" , encoding="utf-8") as f:
        f.write(res.text)

    print(f"Page {page_count} downloaded ✅")

    page_count += 1

Page 1 downloaded ✅
Page 2 downloaded ✅
Page 3 downloaded ✅
Page 4 downloaded ✅
Page 5 downloaded ✅
Page 6 downloaded ✅
Page 7 downloaded ✅
Page 8 downloaded ✅
Page 9 downloaded ✅
Page 10 downloaded ✅
No more pages left 🚫

In [2]:
from bs4 import BeautifulSoup

page_count = 1
all_data=[]

while True:
    try:
        with open(f"web_scraping_projects/quotes{page_count}.html", "r", encoding="utf-8") as f:
            html_content = f.read()
    except FileNotFoundError:
        print("No more files 🚫")
        break

    soup = BeautifulSoup(html_content, "lxml")
    all_quotes = soup.select("div.quote")

    if not all_quotes:
        print("No more quotes 🚫")
        break

    for quote in all_quotes:
        all_tags=[]
        
        for tag in quote.select(".tags .tag"):
            all_tags.append(tag.get_text())


        if "life" in all_tags:
            text= quote.select_one("span.text").get_text()
            author= quote.select_one("small.author").get_text()
            all_data.append([author , text])
        
        # print(text, "-", author)

    # print(f"Page {page_count} done \n")

    page_count += 1

No more files 🚫

In [5]:
import pandas as pd
df=pd.DataFrame(all_data)
# df=pd.DataFrame(all_countries, columns=["name", "population"])
df2=df.copy()

df2.columns = ["author", "text"]
df2.to_csv("cleaned_life_quotes_data/data.csv", index=False)
df2

,author,text
0,Albert Einstein,“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
1,André Gide,“It is better to be hated for what you are than to be loved for what you are not.”
2,Marilyn Monroe,"“This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about.”"
3,Douglas Adams,"“I may not have gone where I intended to go, but I think I have ended up where I needed to be.”"
4,Mark Twain,"“Good friends, good books, and a sleepy conscience: this is the ideal life.”"
5,Allen Saunders,“Life is what happens to us while we are making other plans.”
6,Dr. Seuss,"“Today you are You, that is truer than true. There is no one alive who is Youer than You.”"
7,Albert Einstein,"“Life is like riding a bicycle. To keep your balance, you must keep moving.”"
8,George Bernard Shaw,“Life isn't about finding yourself. Life is about creating yourself.”
9,Ralph Waldo Emerson,“Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day. You shall begin it serenely and with too high a spirit to be encumbered with your old nonsense.”
10,Mark Twain,“The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.”
11,Jimi Hendrix,"“I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.”"
12,Khaled Hosseini,“But better to get hurt by the truth than comforted with a lie.”

In [3]:
import pandas as pd

pd.set_option('display.max_colwidth', None)

df = pd.DataFrame(all_data)
df2 = df.copy()

df2.columns = ["author", "text"]

df2

,author,text
0,Albert Einstein,“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
1,André Gide,“It is better to be hated for what you are than to be loved for what you are not.”
2,Marilyn Monroe,"“This life is what you make it. No matter what, you're going to mess up sometimes, it's a universal truth. But the good part is you get to decide how you're going to mess it up. Girls will be your friends - they'll act like it anyway. But just remember, some come, some go. The ones that stay with you through everything - they're your true best friends. Don't let go of them. Also remember, sisters make the best friends in the world. As for lovers, well, they'll come and go too. And baby, I hate to say it, most of them - actually pretty much all of them are going to break your heart, but you can't give up because if you give up, you'll never find your soulmate. You'll never find that half who makes you whole and that goes for everything. Just because you fail once, doesn't mean you're gonna fail at everything. Keep trying, hold on, and always, always, always believe in yourself, because if you don't, then who will, sweetie? So keep your head high, keep your chin up, and most importantly, keep smiling, because life's a beautiful thing and there's so much to smile about.”"
3,Douglas Adams,"“I may not have gone where I intended to go, but I think I have ended up where I needed to be.”"
4,Mark Twain,"“Good friends, good books, and a sleepy conscience: this is the ideal life.”"
5,Allen Saunders,“Life is what happens to us while we are making other plans.”
6,Dr. Seuss,"“Today you are You, that is truer than true. There is no one alive who is Youer than You.”"
7,Albert Einstein,"“Life is like riding a bicycle. To keep your balance, you must keep moving.”"
8,George Bernard Shaw,“Life isn't about finding yourself. Life is about creating yourself.”
9,Ralph Waldo Emerson,“Finish each day and be done with it. You have done what you could. Some blunders and absurdities no doubt crept in; forget them as soon as you can. Tomorrow is a new day. You shall begin it serenely and with too high a spirit to be encumbered with your old nonsense.”
10,Mark Twain,“The fear of death follows from the fear of life. A man who lives fully is prepared to die at any time.”
11,Jimi Hendrix,"“I'm the one that's got to die when it's time for me to die, so let me live my life the way I want to.”"
12,Khaled Hosseini,“But better to get hurt by the truth than comforted with a lie.”